# Generated by Django 3.1.4 on 2021-02-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognize', '0003_auto_20210209_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
