# Generated by Django 3.1.4 on 2021-01-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='encodings',
            field=models.JSONField(blank=True),
        ),
    ]
