# Generated by Django 3.1.4 on 2021-01-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encode', '0002_auto_20210115_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='encodings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
