# Generated by Django 3.1.4 on 2021-01-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encode', '0003_auto_20210115_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classname',
        ),
        migrations.AddField(
            model_name='classset',
            name='students',
            field=models.ManyToManyField(related_name='classname', to='encode.Student'),
        ),
    ]
