# Generated by Django 3.1.4 on 2021-02-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encode', '0005_auto_20210124_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='classset',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classset',
            name='occourance',
            field=models.IntegerField(default=0),
        ),
    ]
